apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-actions
  namespace: apps
  labels:
    k8s-app: k8-actions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
