apiVersion: apps
kind: Service
metadata:
  name: k8-actions-service
  namespace: apps
  labels:
    k8s-app: k8-actions
spec:
  selector:
    k8s-app: k8-actions
  ports:
  - name: k8-actions-port
    protocol: TCP
    port: 80
    targetPort: 80